config/routes.rb
Rails.application.routes.draw do
  root 'rooms#show'
  resources :scrapes, only: [:index, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @messages = Message.all.limit(500)
  end
end

app/controllers/scrapes_controller.rb
require 'open-uri'
require 'nokogiri'
require 'date'

class ScrapesController < ApplicationController
  def index
  end

  def new
    @day_time = DateTime.now
    root_url = "https://news.yahoo.co.jp/"

    charset = nil
    html = open(root_url) do |f|
      charset = f.charset
      f.read
    end

    doc = Nokogiri::HTML.parse(html, nil, charset)

    site_list = doc.css("ul.toptopics_list")
    data = []
    num = 0
    count = 0
    8.times do
      url = site_list.css("a")[num][:href]
      data.push(url)
      num += 1
      count += 1
    end

    title_data = []
    summary_data = []
    time_data = []

    data.each do |topic_url|
      charset = nil
      topic_html = open(topic_url) do |f|
        charset = f.charset
        f.read
      end
      topic_doc = Nokogiri::HTML.parse(topic_html, nil, charset)
      topic_url_title = topic_doc.css("h2.newsTitle")
      title_data.push(topic_url_title.css("a").text)

      topic_url_summary = topic_doc.css("p.hbody")
      summary_data.push(topic_url_summary.text)

      topic_url_time = topic_doc.css(".topicsName")
      time_data.push(topic_url_time.css("span.date").text)
    end

    @title_datas = title_data
    @summary_datas = summary_data
    @time_datas = time_data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/scrapes_helper.rb
module ScrapesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebsocketChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="webchat-form__name">
  <%= message.name %>
</div>
<div class="webchat-form__message">
  <%= message.content %>
</div>

app/views/rooms/show.html.erb
<div class="webchat">
  <h1 class="webchat__title">WebSocketでチャット</h1>
  <%= link_to "スクレイピングページ", new_scrape_path, class: "webchat__link" %>
  <div class="webchat-describe">
    <h2>環境</h2>
    <ul>
      <li class="webchat-describe__item">rails5.2.2</li>
      <li class="webchat-describe__item">ruby2.3.1</li>
      <li class="webchat-describe__item">mysql</li>
    </ul>
    <p>railsのAction Cableの機能を使用してWebSocketでの通信を実現しました。</p>
  </div>
  <div class="webchat-form">
    <form>
      <label class="webchat-form__cin">名前を入力してください</label>
    </br>
      <input class="webchat-form__input-name" type="text">
    </br>
      <label class="webchat-form__cin">コメントを入力してください</label>
    </br>
      <input class="webchat-form__input-text" type="text">
      <input class="webchat-form__button" type="submit" data-behavior="room_speaker">
    </form>
    <span class="webchat-form__n-title">名前</span>
    <span class="webchat-form__c-title">コメント</span>
    <div class="webchat-form__messages">
      <%= render @messages %>
    </div>
  </div>
</div>

app/views/scrapes/new.html.erb
<div class="scrapes">
  <h1 class="scrapes__time-now"><%= "#{@day_time.year}年#{@day_time.month}月#{@day_time.mday}日  #{@day_time.hour}時#{@day_time.min}分" %>時点のyahoo Pick up記事</h1>
  <%= link_to "戻る", root_path, class: "webchat__link" %>
  <% @title_datas.zip(@time_datas,@summary_datas).each do |title_data, time_data, summary_data| %>
    <div class="scrapes__box">
      <div class="scrapes__title">
        <h3><%= title_data %></h3>
      </div>
      <div class="scrapes__time">
        <h4><%= time_data %></h4>
      </div>
      <div class="scrapes__summary"><%= summary_data %></div>
    </div>
  <% end %>
</div>